// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwkFstODaKooMpZCSVzNMFSXWuVkVjrzk',
    appId: '1:1057609791463:web:18d77c59f14336f6ee6f42',
    messagingSenderId: '1057609791463',
    projectId: 'agentblue-d83e5',
    authDomain: 'agentblue-d83e5.firebaseapp.com',
    storageBucket: 'agentblue-d83e5.firebasestorage.app',
    measurementId: 'G-K90N4XNJN0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGM-7wNXlldDdzp8OIMwJZsuWq6uO_QTs',
    appId: '1:1057609791463:ios:b208f744d45dd0edee6f42',
    messagingSenderId: '1057609791463',
    projectId: 'agentblue-d83e5',
    storageBucket: 'agentblue-d83e5.firebasestorage.app',
    iosBundleId: 'com.example.agentBlueDesktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwkFstODaKooMpZCSVzNMFSXWuVkVjrzk',
    appId: '1:1057609791463:web:c5bd5a7fd03be12dee6f42',
    messagingSenderId: '1057609791463',
    projectId: 'agentblue-d83e5',
    authDomain: 'agentblue-d83e5.firebaseapp.com',
    storageBucket: 'agentblue-d83e5.firebasestorage.app',
    measurementId: 'G-V6GDS42QQ5',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGM-7wNXlldDdzp8OIMwJZsuWq6uO_QTs',
    appId: '1:1057609791463:ios:b208f744d45dd0edee6f42',
    messagingSenderId: '1057609791463',
    projectId: 'agentblue-d83e5',
    storageBucket: 'agentblue-d83e5.firebasestorage.app',
    iosBundleId: 'com.example.agentBlueDesktop',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP23MArskeNuV2SpSpjlCFmGGJfK--e5U',
    appId: '1:1057609791463:android:6ec422c47f297cc2ee6f42',
    messagingSenderId: '1057609791463',
    projectId: 'agentblue-d83e5',
    storageBucket: 'agentblue-d83e5.firebasestorage.app',
  );

}